set shell := ["bash", "-eu", "-o", "pipefail", "-c"]

import './src/setup.just'
import './src/install_dependencies.just'
import './src/extraction.just'

default: clean install-dependencies extract-all

# ---------------------------------------------------------------------------
# 💻  DEBUG
# ---------------------------------------------------------------------------
#extract-alldata:
#    @for f in ./PCBANKS/*.pak; do \
#        gum spin --spinner dot --title "Decoding $f" -- ./out/hgpaktool "$f" -O ./out/EXTRACTED > /dev/null; \
#    done
#    @shopt -s globstar nullglob
#    @for f in ./out/EXTRACTED/**/*.mbin; do \
#        dir="$(dirname "$f")"; \
#        base="$(basename "$f" .mbin)"; \
#        out="$dir/$base.MXML"; \
#        if [[ -f "$out" ]]; then \
#            continue; \
#        fi; \
#        if ! gum spin --spinner dot --title "Decoding $f" -- \
#            ./out/mbincompiler -y -d "$dir" "$f" > /dev/null; then \
#            echo "⚠️  Failed to decode $f (invalid MBIN?)"; \
#            continue; \
#        fi; \
#    done;
#
#extract-deps:
#    @gum style --border rounded --border-foreground 45 --margin "1 0 0 0" --padding "0 3" --width 80 --align left "⚙️ Extracting dependencies"
#    @gum spin --spinner dot --title "Extracting NMSARC.MetadataEtc.pak" -- ./out/hgpaktool ./PCBANKS/NMSARC.MetadataEtc.pak -O ./out/EXTRACTED > /dev/null;
#    @gum spin --spinner dot --title "Extracting NMSARC.Precache.pak" -- ./out/hgpaktool ./PCBANKS/NMSARC.Precache.pak -O ./out/EXTRACTED > /dev/null;
#    @gum spin --spinner dot --title "Extracting NMSARC.TexUI.pak" -- ./out/hgpaktool ./PCBANKS/NMSARC.TexUI.pak -O ./out/EXTRACTED > /dev/null;
#    @for f in ./out/EXTRACTED/metadata/reality/tables/*.mbin; do \
#        dir="$(dirname "$f")"; \
#        base="$(basename "$f" .mbin)"; \
#        out="$dir/$base.MXML"; \
#        if [[ -f "$out" ]]; then \
#            continue; \
#        fi; \
#        if ! gum spin --spinner dot --title "Decoding $f" -- \
#            ./out/mbincompiler -y -d "$dir" "$f" > /dev/null; then \
#            echo "⚠️  Failed to decode $f (invalid MBIN?)"; \
#            continue; \
#        fi; \
#    done;
#
#